name: GPSA CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install your package (editable mode) and dev extras
          pip install -e .[dev]
          # install the pinned runtime deps
          pip install -r requirements.txt

      - name: Run lint & tests
        run: |
          flake8
          pytest tests

      - name: Sanity‐check example
        run: |
          python examples/grid_example.py

