name: Upgrade requirements

on:
  schedule:
    - cron: '0 2 * * 1'   # every Monday at 02:00 UTC
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install "setuptools<69" wheel

      - name: Upgrade requirements
        run: |
          pip-compile --upgrade --constraint constraints.txt requirements.in

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: upgrade dependencies"
          branch: upgrade-deps-${{ github.run_id }}
          title: "Upgrade dependencies via pip-compile"
          labels: dependencies, automated
